"""empty message

Revision ID: 02996752fe0a
Revises: bc1237c618d5
Create Date: 2026-04-30 09:35:31.471498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02996752fe0a'
down_revision = 'bc1237c618d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.alter_column('exam_time_in',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('exam_time_out',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('log_entry_examinee_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'examinee', ['examinee'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('log_entry_examinee_fkey'), 'examinee', ['examinee'], ['id'])
        batch_op.alter_column('exam_time_out',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('exam_time_in',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
