"""empty message

Revision ID: 2bac2469c563
Revises: 990bebfac20c
Create Date: 2026-04-30 08:37:22.201382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bac2469c563'
down_revision = '990bebfac20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_kit', sa.Integer(), nullable=False))
        batch_op.alter_column('examinee',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'exam_kit', ['exam_kit'], ['kit_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('examinee',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('exam_kit')

    # ### end Alembic commands ###
