"""empty message

Revision ID: 52224c6361c3
Revises: 8917df0661f0
Create Date: 2026-04-30 08:46:58.273974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52224c6361c3'
down_revision = '8917df0661f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
