"""add log entries

Revision ID: 7248f398122e
Revises: 3d9068eba588
Create Date: 2026-04-29 16:46:59.937557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7248f398122e'
down_revision = '3d9068eba588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('examinee', sa.Integer(), nullable=False),
    sa.Column('reg_time', sa.DateTime(), nullable=False),
    sa.Column('exam_time_in', sa.DateTime(), nullable=False),
    sa.Column('exam_time_out', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examinee'], ['examinee.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_entry')
    # ### end Alembic commands ###
