"""empty message

Revision ID: 79305cfffc29
Revises: c7f9d4a0b6e2
Create Date: 2026-05-14 09:12:07.097694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79305cfffc29'
down_revision = 'c7f9d4a0b6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_kit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exam_kit_examinee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'examinee', ['examinee_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('examinee_picture', schema=None) as batch_op:
        batch_op.alter_column('post_test',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('post_conf',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_examinee_picture_examinee_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('examinee_picture_examinee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'examinee', ['examinee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_log_entry_examinee'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_log_entry_examinee'), ['examinee'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('examinee_picture', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('examinee_picture_examinee_id_fkey'), 'examinee', ['examinee_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_examinee_picture_examinee_id'), ['examinee_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('post_conf',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('post_test',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    with op.batch_alter_table('exam_kit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exam_kit_examinee_id_fkey'), 'examinee', ['examinee_id'], ['id'])

    # ### end Alembic commands ###
