"""empty message

Revision ID: 863022dbaa53
Revises: 
Create Date: 2026-04-30 00:30:28.371056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863022dbaa53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examinee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_kit',
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('examinee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['examinee_id'], ['examinee.id'], ),
    sa.PrimaryKeyConstraint('kit_id')
    )
    op.create_table('examinee_picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pre_test', sa.LargeBinary(), nullable=False),
    sa.Column('post_test', sa.LargeBinary(), nullable=False),
    sa.Column('pre_conf', sa.Float(), nullable=False),
    sa.Column('post_conf', sa.Float(), nullable=False),
    sa.Column('examinee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examinee_id'], ['examinee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_entry',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('examinee', sa.Integer(), nullable=False),
    sa.Column('reg_time', sa.DateTime(), nullable=False),
    sa.Column('exam_time_in', sa.DateTime(), nullable=False),
    sa.Column('exam_time_out', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examinee'], ['examinee.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_entry')
    op.drop_table('examinee_picture')
    op.drop_table('exam_kit')
    op.drop_table('examinee')
    # ### end Alembic commands ###
