"""empty message

Revision ID: 8917df0661f0
Revises: 2bac2469c563
Create Date: 2026-04-30 08:41:37.923101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8917df0661f0'
down_revision = '2bac2469c563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.alter_column('exam_kit',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.alter_column('exam_kit',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
