"""empty message

Revision ID: 990bebfac20c
Revises: 863022dbaa53
Create Date: 2026-04-30 08:35:43.583401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990bebfac20c'
down_revision = '863022dbaa53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('examinee', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examinee'], ['examinee.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_log')
    # ### end Alembic commands ###
