"""change examinee.picture to png

Revision ID: b157ccc0b141
Revises: 7248f398122e
Create Date: 2026-04-29 17:28:01.049024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b157ccc0b141'
down_revision = '7248f398122e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinee', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinee', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)

    # ### end Alembic commands ###
