"""add examinee picture table

Revision ID: b5f2f2e9db99
Revises: d727213baa92
Create Date: 2026-04-29 16:33:05.241377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5f2f2e9db99'
down_revision = 'd727213baa92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examinee_picture')
    op.drop_table('examinee')
    op.drop_table('exam_kit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_kit',
    sa.Column('kit_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submitted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('examinee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['examinee_id'], ['examinee.id'], name=op.f('exam_kit_examinee_id_fkey')),
    sa.PrimaryKeyConstraint('kit_id', name=op.f('exam_kit_pkey'))
    )
    op.create_table('examinee',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('picture', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('examinee_pkey'))
    )
    op.create_table('examinee_picture',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pre_test', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('post_test', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('examinee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['examinee_id'], ['examinee.id'], name=op.f('examinee_picture_examinee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('examinee_picture_pkey'))
    )
    # ### end Alembic commands ###
