"""empty message

Revision ID: bc1237c618d5
Revises: 52224c6361c3
Create Date: 2026-04-30 09:25:31.255434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1237c618d5'
down_revision = '52224c6361c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_log_examinee_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('event_log_exam_kit_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'examinee', ['examinee'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exam_kit', ['exam_kit'], ['kit_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_log_exam_kit_fkey'), 'exam_kit', ['exam_kit'], ['kit_id'])
        batch_op.create_foreign_key(batch_op.f('event_log_examinee_fkey'), 'examinee', ['examinee'], ['id'])

    # ### end Alembic commands ###
